version: 2
jobs:
  build:
    working_directory: ~/angular-7-electron-orm-linux
    docker:
    - image: electronuserland/builder:wine-mono
    steps:
    - checkout
    - run: npm install
    - run: npm run electron:linux
    - run: npm run electron:windows
    - store_artifacts:
        path: app-builds
        destination: builds
workflows:
  version: 2
  workflow:
    jobs:
    - build