version: 2
jobs:
  build:
    working_directory: ~/angular-7-electron-orm
    docker:
      - image: electronuserland/builder:latest
    steps:
      - checkout
      - run: npm install
      - run: npm run electron-build
      # - store_artifacts:
      #     path: app-builds
      #     destination: builds
