version: 2
jobs:
  build:
    docker:
      - image: node:lts-alpine
    steps:
      - run: npm install
      - run: npm run electron:linux
      - run: npm run electron:windows
      - run: npm run electron:mac
      - store_artifacts:
          path: /app-builds
          destination: builds
