version: 2
jobs:
  build:
    working_directory: ~/angular-7-electron-orm
    docker:
      - image: node:lts-alpine
    steps:
      - checkout
      - run: npm install
      - run: npm run electron:linux
      - run: npm run electron:windows
      - run: npm run electron:mac
      - store_artifacts:
          path: app-builds
          destination: builds
